title: "Jason's Simple Blog"
description: |
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
author: 'Jason23347'
sidebar-avatar: //gravatar.com/avatar/fdaf3db072f81d12d1a1d8edb8b269ab?s=100
language: zh
timezone: 'asia/shanghai'
auto_spacing: true

# URL
## If your site is put in a subdirectory, set url as 'http://example.com/child' and root as '/child/'
url: https://jason23347.github.io
root: /
permalink: :year/:month-:day-:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# SNS settings
# 一些社交平台地址，支持以下几种：
github_username: Jason23347

# Extensions
## Plugins: https://hexo.io/plugins/
plugins:
  hexo-generator-feed
## Themes: https://hexo.io/themes/
theme: hexo-theme-aircloud

# Theme settings
post_style:
  indent: 0

# Custom Setting End
# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archive
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Category & Tag
default_category: 折腾
category_map:
tag_map:

search:
  path: search.json
  field: post

archive_generator:
  enabled: true
  per_page: 8
  yearly: true
  monthly: true
  daily: false
  order_by: -date

category_generator:
  per_page: 4
  order_by: -date

tag_generator:
  per_page: 8
  order_by: -date

html_minifier:
  collapseBooleanAttributes: true
  collapseWhitespace: true
  removeComments: true
  removeEmptyAttributes: true
  removeScriptTypeAttributes: true
  removeStyleLinkTypeAttributes: true
  minifyJS: true
  minifyCSS: true

cdn_filter:
  enable: false

text_autospace_filter:
  enable: true
  tag_name: 'hl'
  entry: 'body'

highlight:
  enable: true
  line_number: false
